const router = require('express').Router();
const service = require('./service');
const { verifyToken } = require('../../middleware/authMiddleware');
const { MANAGEMENT_ROLES, requireRoles } = require('../../middleware/authorizationMiddleware');
router.use(verifyToken, requireRoles(MANAGEMENT_ROLES.SUPER_ADMIN, MANAGEMENT_ROLES.ADMIN));
const run = (fn) => async (req, res, next) => { try { res.json(await fn(req)); } catch (error) { next(error); } };
router.get('/', (_req, res) => res.status(404).json({ error: 'Report unavailable' }));
router.get('/:id/movements', (_req, res) => res.status(404).json({ error: 'Report unavailable' }));
router.post('/:id/movements', run((req) => service.change(req.params.id, req.body, req.user)));
module.exports = router;
