/**
 * Job ID Service — Centralized, backend-only job numbering.
 *
 * Generates job IDs in format: POMAT###/V###/D###/T###/J####
 * e.g. "POMAT003/V001/D004/T010/J0004"
 *
 * Design principles:
 *  1. The backend is the single source of truth for job numbering.
 *  2. One shared sequential counter per Purchase Order.
 *  3. All quarries and sites share the same counter for a given PO.
 *  4. Firestore transactions guarantee atomicity — no duplicates, no gaps
 *     under concurrent requests.
 *  5. The frontend only builds the "job key" (everything before the J number).
 *     The J number is ALWAYS generated by this service.
 */
const { db } = require('../../config/firebase');

const COUNTER_COLLECTION = 'jobCounters';

/**
 * Generate the next unique job ID for a given purchase order.
 *
 * @param {string} purchaseOrderId - The Firestore doc ID of the purchase order
 * @param {string} jobKey - The job key built by the client, e.g. "POMAT003/V001/D004/T010"
 *                          (everything before the final /J#### segment)
 * @returns {Promise<{ jobId: string, jobNumber: number }>}
 */
async function generateJobIdForPO(purchaseOrderId, jobKey) {
  if (!purchaseOrderId) {
    throw new Error('purchaseOrderId is required to generate a job ID');
  }

  // Normalize the job key: strip any trailing /J#### or timestamp suffix the client may have sent
  const cleanKey = jobKey
    ? jobKey.replace(/\/J\d+(-\w+)?$/, '').replace(/-\w+$/, '')
    : '';

  // Derive the counter document ID from the purchaseOrderId.
  // purchaseOrderId is already in the format "POMAT###-V###" (slash replaced with dash)
  // but let's also handle raw poNumber like "POMAT003/V001"
  const counterId = purchaseOrderId.replace(/\//g, '-');

  const counterRef = db.collection(COUNTER_COLLECTION).doc(counterId);

  const nextNumber = await db.runTransaction(async (transaction) => {
    const doc = await transaction.get(counterRef);

    let current = 0;
    if (doc.exists) {
      current = doc.data().nextJobNumber || 0;
    }

    // Also perform a belt-and-suspenders check against existing delivery orders
    // to ensure we never issue a duplicate number (handles counter resets / migrations)
    let maxExistingNumber = 0;
    try {
      // No ordering is needed—we scan these records only to find the highest
      // J number. Avoiding orderBy keeps this safety check on Firestore's
      // single-field index and prevents job creation from needing a composite
      // index before it can proceed.
      const existingSnapshot = await transaction.get(
        db.collection('deliveryOrders')
          .where('purchaseOrderId', '==', purchaseOrderId)
          .limit(100)
      );
      existingSnapshot.forEach((existingDoc) => {
        const existingJobId = existingDoc.data().jobId || '';
        const match = existingJobId.match(/\/J(\d+)$/);
        if (match) {
          const num = parseInt(match[1], 10);
          if (num > maxExistingNumber) maxExistingNumber = num;
        }
      });
    } catch (queryErr) {
      // If the composite index doesn't exist yet, fall back to counter only.
      // This is non-fatal — the counter is the primary source of truth.
      console.warn('[jobIdService] Could not query existing jobs for safety check:', queryErr.message);
    }

    // Use whichever is higher: the atomic counter or existing max
    const effectiveCurrent = Math.max(current, maxExistingNumber);
    const next = effectiveCurrent + 1;

    transaction.set(counterRef, {
      nextJobNumber: next,
      purchaseOrderId,
      updatedAt: new Date().toISOString(),
    }, { merge: true });

    return next;
  });

  const jobNumber = nextNumber;
  const paddedNumber = String(jobNumber).padStart(4, '0');
  const jobId = `${cleanKey}/J${paddedNumber}`;

  console.log(`[jobIdService] Generated job ID: ${jobId} (PO: ${purchaseOrderId}, number: ${jobNumber})`);

  return { jobId, jobNumber };
}

/**
 * Peek at the next job number for a PO without incrementing it.
 * Used for previews — does NOT consume a number.
 *
 * @param {string} purchaseOrderId
 * @returns {Promise<number>}
 */
async function peekNextJobNumber(purchaseOrderId) {
  const counterId = purchaseOrderId.replace(/\//g, '-');
  const counterRef = db.collection(COUNTER_COLLECTION).doc(counterId);

  const doc = await counterRef.get();
  let current = 0;
  if (doc.exists) {
    current = doc.data().nextJobNumber || 0;
  }
  return current + 1;
}

module.exports = { generateJobIdForPO, peekNextJobNumber };
